// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReturnOK struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnOK) Reset()         { *m = ReturnOK{} }
func (m *ReturnOK) String() string { return proto.CompactTextString(m) }
func (*ReturnOK) ProtoMessage()    {}
func (*ReturnOK) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_e78f0193863e7fb2, []int{0}
}
func (m *ReturnOK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnOK.Unmarshal(m, b)
}
func (m *ReturnOK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnOK.Marshal(b, m, deterministic)
}
func (dst *ReturnOK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnOK.Merge(dst, src)
}
func (m *ReturnOK) XXX_Size() int {
	return xxx_messageInfo_ReturnOK.Size(m)
}
func (m *ReturnOK) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnOK.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnOK proto.InternalMessageInfo

func (m *ReturnOK) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateUserEvent struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserEvent) Reset()         { *m = UpdateUserEvent{} }
func (m *UpdateUserEvent) String() string { return proto.CompactTextString(m) }
func (*UpdateUserEvent) ProtoMessage()    {}
func (*UpdateUserEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_e78f0193863e7fb2, []int{1}
}
func (m *UpdateUserEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserEvent.Unmarshal(m, b)
}
func (m *UpdateUserEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserEvent.Marshal(b, m, deterministic)
}
func (dst *UpdateUserEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserEvent.Merge(dst, src)
}
func (m *UpdateUserEvent) XXX_Size() int {
	return xxx_messageInfo_UpdateUserEvent.Size(m)
}
func (m *UpdateUserEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserEvent proto.InternalMessageInfo

func (m *UpdateUserEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserEvent) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*ReturnOK)(nil), "user.ReturnOK")
	proto.RegisterType((*UpdateUserEvent)(nil), "user.UpdateUserEvent")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	UpdateUser(ctx context.Context, in *UpdateUserEvent, opts ...grpc.CallOption) (*ReturnOK, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserEvent, opts ...grpc.CallOption) (*ReturnOK, error) {
	out := new(ReturnOK)
	err := c.cc.Invoke(ctx, "/user.UserService/UpdateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	UpdateEmail(context.Context, *UpdateUserEvent) (*ReturnOK, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UpdateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateEmail(ctx, req.(*UpdateUserEvent))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateEmail",
			Handler:    _UserService_UpdateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_e78f0193863e7fb2) }

var fileDescriptor_user_e78f0193863e7fb2 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x54, 0xb8, 0x38, 0x82, 0x52,
	0x4b, 0x4a, 0x8b, 0xf2, 0xfc, 0xbd, 0x85, 0x24, 0xb8, 0xd8, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3,
	0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x25, 0x6b, 0x2e, 0xfe, 0xd0, 0x82,
	0x94, 0xc4, 0x92, 0xd4, 0xd0, 0xe2, 0xd4, 0x22, 0xd7, 0xb2, 0xd4, 0xbc, 0x12, 0x21, 0x21, 0x2e,
	0x96, 0xbc, 0xc4, 0x5c, 0x98, 0x4a, 0x30, 0x5b, 0x48, 0x84, 0x8b, 0x35, 0x35, 0x37, 0x31, 0x33,
	0x47, 0x82, 0x09, 0x2c, 0x08, 0xe1, 0x18, 0x39, 0x71, 0x71, 0x83, 0xb4, 0x05, 0xa7, 0x16, 0x95,
	0x65, 0x26, 0xa7, 0x0a, 0x19, 0x73, 0x71, 0x21, 0xcc, 0x12, 0x12, 0xd5, 0x03, 0x3b, 0x09, 0xcd,
	0x74, 0x29, 0x3e, 0x88, 0x30, 0xcc, 0x69, 0x49, 0x6c, 0x60, 0x37, 0x1b, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xe5, 0x68, 0xff, 0x11, 0xc1, 0x00, 0x00, 0x00,
}
